name: Test callable workflows
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: ks-test-20230616
jobs:
  cluster:
    uses: ./.github/workflows/gke.yaml
    with:
      name: ${{ inputs.name }}
      deploy: true
  galaxy:
    uses: ./.github/workflows/install-galaxy.yaml
    with:
      chart: anvil/galaxykubeman
      version: "2.7.0"
      prefix: ${{ inputs.name }}
  teardown:
    uses: ./github/workflows/gke.yaml
    with:
      name: ${{ inputs.name }}
      deploy: false
