name: Test callable workflows
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
        default: ks-test-20230616
        description: "Name used for the cluster, namespace, and generated ID values."
      type:
        type: choice
        default: edge
        options: ['edge', 'production']
        description: "Are we testing production or dev tools"
      chunk:
        type: int
        default: 3
      idp:
        type: string
        default: 'projects/526897014808/locations/global/workloadIdentityPools/galaxy-tests-identity-pool/providers/gxy-tests-provider'
      account:
        type: string
        default: 'galaxy-tests-repo-actions-sa@anvil-and-terra-development.iam.gserviceaccount.com'

jobs:
  cluster:
    uses: ./.github/workflows/gke.yaml
    with:
      name: ${{ inputs.name }}
      deploy: true
      idp: ${{ inputs.idp }}
      account: ${{ inputs.account }}
  galaxy:
    needs: cluster
    uses: ./.github/workflows/install-galaxy.yaml
    with:
      chart: anvil/galaxykubeman
      version: "2.7.0"
      prefix: ${{ inputs.name }}
      type: ${{ inputs.type }}
      idp: ${{ inputs.idp }}
      account: ${{ inputs.account }}
#      token: ${{ secrets.GIT_TOKEN }}
  test:
    needs: galaxy
    uses: ./.github/workflows/tool-tests.yaml
    with:
      prefix: ${{ inputs.name }}
      chunk: ${{ inputs.chunk }}
      type: ${{ inputs.type }}
      idp: ${{ inputs.idp }}
      account: ${{ inputs.account }}
  teardown:
    needs: [cluster, test]
    if: always()
    uses: ./.github/workflows/gke.yaml
    with:
      name: ${{ inputs.name }}
      deploy: false
      idp: ${{ inputs.idp }}
      account: ${{ inputs.account }}
